config/routes.rb
Rails.application.routes.draw do

  root to: 'students#index'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'help',       to:  'static_pages#help'
  
  get 'about',      to:  'static_pages#about'
  
  get 'contact',    to:  'static_pages#contact'
  
  get 'signup',     to:  'users#new'
  
  get 'login',      to:  'sessions#new'
  
  post 'login',     to:  'sessions#create'
  
  delete 'logout',  to:  'sessions#destroy'
  
  resources              :users
  
  resources             :account_activations, only: [:edit]
  
  resources             :password_resets,     only: [:new, :create, :edit, :update]
  
  resources             :events
  
  resources   :students do
    collection { post :import }
  end
  
  
  resources             :event_attendance_records do
    member do
      patch 'present_toggle'
    end
    
    member do
      patch 'fed_toggle'
    end
    
    member do
      patch 'milk_only_toggle'
    end
    
    member do
      patch 'brought_lunch_toggle'
    end
  end

end

app/models/event_attendance_record.rb
class EventAttendanceRecord < ActiveRecord::Base
  belongs_to :event
  belongs_to :student
  
  def present_toggle
    self.present = !self.present
    self.save
  end
  
  def fed_toggle
    self.fed = !self.fed
    self.save
  end
  
  def milk_only_toggle
    self.milk_only = !self.milk_only
    self.save
  end
  
  def brought_lunch_toggle
    self.brought_lunch = !self.brought_lunch
    self.save
  end
  
  private
  
end

app/controllers/event_attendance_record_controller.rb
class EventAttendanceRecordController < ApplicationController
  before_action :logged_in_user
  
  def new
    @event_attendance_record = EventAttendanceRecord.new
  end
  
  def create
  end
  
  def index
    @event_attendance_record = EventAttendanceRecord.paginate(page: params[:page])
  end

  def show
    @event_attendance_record = EventAttendanceRecord.find(params[:id])
  end

  def edit
    @event_attendance_record = EventAttendanceRecord.find(params[:id])
  end
  
  def update
    @event_attendance_record = EventAttendanceRecord.find(params[:id])
    if @event_attendance_record.update_attributes(event_attendance_record_params)
      flash[:success] = "Event Attendance Record updated"
      redirect_to @event_attendance_record
    else
      render 'edit'
    end
  end
    
  
  private
  
    #Confirms a logged-in user.
    def logged_in_user
        unless logged_in?
          store_location
          flash[:danger] = "Please log in."
          redirect_to login_url
        end
    end
  
    def event_attendance_record_params
      params.require(:event_attendance_record).permit(:id)
    end
end

app/controllers/event_attendance_records_controller.rb
class EventAttendanceRecordsController < ApplicationController
  before_action :logged_in_user
  
  def new
    @event_attendance_record = EventAttendanceRecord.new
  end
  
  def create
    
  end
  
  def index
    @event_attendance_record = EventAttendanceRecord.paginate(page: params[:page])
  end

  def show
    @event_attendance_record = EventAttendanceRecord.find(params[:id])
  end

  def edit
    @event_attendance_record = EventAttendanceRecord.find(params[:id])
  end
  
  def update
    puts 'in update'
    @event_attendance_record = EventAttendanceRecord.find(params[:id])
    if @event_attendance_record.update_attributes(event_attendance_record_params)
      puts 'success'
      flash[:success] = "Event Attendance Record updated"
      redirect_to @event_attendance_record
    else
      puts 'errors'
      puts event_attendance_record.errors
      render 'edit'
    end
  end
  
  def present_toggle
    ear = EventAttendanceRecord.find(params[:id])
    ear.present_toggle
    redirect_to ear.event
  end
  
  def 
  
  def fed_toggle
    ear = EventAttendanceRecord.find(params[:id])
    ear.fed_toggle
    redirect_to ear.event
  end
  
  def milk_only_toggle
    ear = EventAttendanceRecord.find(params[:id])
    ear.milk_only_toggle
    redirect_to ear.event
  end
  
  def brought_lunch_toggle
    ear = EventAttendanceRecord.find(params[:id])
    ear.brought_lunch_toggle
    redirect_to ear.event
  end
    
  
  private
  
    #Confirms a logged-in user.
    def logged_in_user
        unless logged_in?
          store_location
          flash[:danger] = "Please log in."
          redirect_to login_url
        end
    end
  
    def event_attendance_record_params
      params.require(:event_attendance_record).permit(:present, :brought_lunch, :fed, :milk_only)
    end
    
    def student_params
      params.require(:student).permit(:fname, :lname, :my_teacher, :grade)
    end
end

app/helpers/event_attendance_record_helper.rb
module EventAttendanceRecordHelper
end

app/views/event_attendance_records/_event_attendance_record.html.erb
<div class="table table-striped table-bordered">
    <table>
      <tr>
        <td><%= event_attendance_record.student.fname %></td>
        <td><%= event_attendance_record.student.lname %></td>
        <td><%= event_attendance_record.student.my_allergies %></td>
        <td><%= event_attendance_record.student.my_teacher %></td>
        <td><%= event_attendance_record.present %>
        <%= link_to "present toggle", present_toggle_event_attendance_record_path(event_attendance_record), method: :patch %>
        </td>
        <td><%= event_attendance_record.brought_lunch %> <%= link_to "brought_lunch toggle", brought_lunch_toggle_event_attendance_record_path(event_attendance_record), method: :patch %></td>
        <td><%= event_attendance_record.fed %> <%= link_to "fed toggle", fed_toggle_event_attendance_record_path(event_attendance_record), method: :patch %></td> 
        <td><%= event_attendance_record.milk_only %> <%= link_to "milk only toggle", milk_only_toggle_event_attendance_record_path(event_attendance_record), method: :patch %></td>
        <td><%= link_to 'Edit', edit_event_attendance_record_path(event_attendance_record) %></td>
      </tr>
    </table>
</div>

app/views/event_attendance_records/_form.html.erb
<%= form_for(@event_attendance_record) do |f| %>
    <%#= render 'shared/error_messages' %>
    
    <%#= f.label :name %> Add Event Name & ID (don't allow id to change)<br />
    <%#= f.text_field :name, class: 'form_control' %>
    
    <%= f.label :present %>
    <%= f.check_box :present, class: 'form_control' %>
    
    <%= f.label :brought_lunch %>
    <%= f.check_box :brought_lunch, class: 'form_control' %>
    
    <%= f.label :fed %>
    <%= f.check_box :fed, class: 'form_control' %>
    
    <%= f.label :milk_only %>
    <%= f.check_box :milk_only, class: 'form_control' %>
    
    <%= f.submit "Save changes", class: "btn btn-primary" %>
<% end %>

app/views/event_attendance_records/create.html.erb
<h1>Event Attendance Record Students List</h1>

<%#= will_paginate %>

<ul class="students">
        <%= render '/students/student' %>
</ul>

<%#= will_paginate %>

app/views/event_attendance_records/edit.html.erb
<% provide(:title, 'Edit Event Attendance Record') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update Event Attendance Record</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    </div>
  </div>
</div>

app/views/event_attendance_records/index.html.erb
<h1>Event Attendance Record List</h1>

<%#= will_paginate %>

<ul class="event_attendance_record">
        <%= render @event_attendance_record %>
</ul>

<%#= will_paginate %>

app/views/event_attendance_records/show.html.erb
<% provide(:title, @event_attendance_record.id) %>
<div class="row">
    <aside class="col-md-4">
        <section class="user_info">
           <h1>
               <%= @event_attendance_record.id %>
           </h1>
        </section>
    </aside>
</div>
<div class="table table-striped table-bordered">
  <h1><%= @event_attendance_record.event.name %></h1>
    <table>
      <thead class="thead">
        <tr>
          <th>Student First Name</th>
          <th>Student Last Name</th>
          <th>Allergies</th>
          <th>Teacher</th>
          <th>Present</th>
          <th>Brought Lunch</th>
          <th>Fed</th>
          <th>Milk Only</th>
          <th>Show</th>
          <th>Edit</th>
          <th>Destroy</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tr>
        <td><%= @event_attendance_record.student.fname %></td>
        <td><%= @event_attendance_record.student.lname %></td>
        <td><%= @event_attendance_record.student.my_allergies %></td>
        <td><%= @event_attendance_record.student.my_teacher %></td>
        <td><%= @event_attendance_record.present %></td>
        <td><%= @event_attendance_record.brought_lunch %></td>
        <td><%= @event_attendance_record.fed %></td>
        <td><%= @event_attendance_record.milk_only %></td>
        <td><%= link_to 'Show', @event_attendance_record %></td>
        <td><%= link_to 'Edit', edit_event_attendance_record_path(@event_attendance_record) %></td>
        <td><%= link_to 'Destroy', @event_attendance_record, method: :delete,
                                         data: { confirm: 'Are you sure?' } %></td>
      </tr>
    </table>
</div>